### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Eugenepolyt/Java.ProductList#1]
1. Всё-таки уникальной характеристикой товара является его код, а не имя. И было бы разумно во всех методах, которые принимают имя, принимать код товара.
2. Название товара это тоже характеристика товара, а у вас в классе `Product` его нет. Количество, напротив, не является его характеристикой, возможно стоит отделить его от класса `Product` (а оно от вас вообще требовалось?).
3. Зачем поле `count` в `ProductList`? Судя по тому, что в `add` у вас оно ещё и считает как-то багованно.
4. Почитайте документацию к `Map.get`/`Map.put`/`Map.remove`, в частности, про возвращаемые значения. (Почти) везде где вы делаете `containsKey`, его делать не нужно.
5. Метод `getMap` точно не должен быть публичным. Через него можно получить ссылку на внутреннюю мапу и изменять содержимое прейскуранта минуя API вашего класса. Если хотите подглядывать в эту мапу в тестах, то лучше сделать поле package-private, а метод убрать.
6. Ваши классы, кстати, хорошо бы перенести из default package в пакет.
7. В тестах вы проверяете возвращаемые значения методов, но не проверяете что прейскурант действительно изменился корректно.
8. Название класса `test` следует написать с большой буквы.
9. Вроде как цена у вас корректно представлена в рублях и копейках, а `getPrice` возвращает `float`. `float` — это, пожалуй, самое худшее представление для денежной суммы. Лучше добавьте отдельный класс для денежной суммы (или используйте стандартный, но более подходящий тип).

**Comment by gagarski** [comment]
10. При создании продукта цену хорошо бы проверять на корректность.

**Comment by gagarski** [comment]
1. Возвращать результат `add` и `delete` в виде строки плохо. Возвращать то, что вовзращают соответствующие методы `map` лучше. Печатать тоже ничего не нужно (лучше вообще нигде).
2. Переименовывать и изменять цену товара Default с ценой 1 рубль 1 копейка нельзя. Что-то вы перемудрили с getOrDefault, там всё гораздо проще.
3. В getPrice лучше инвертировать условие, а тело else вынести наружу.
4. Два `BigDecimal`а для цены в Product многовато. Одного должно хватить (в getPrice-то хватает).

**Comment by Eugenepolyt** [comment]
> 1. Возвращать результат `add` и `delete` в виде строки плохо. Возвращать то, что вовзращают соответствующие методы `map` лучше. Печатать тоже ничего не нужно (лучше вообще нигде).
> 2. Переименовывать и изменять цену товара Default с ценой 1 рубль 1 копейка нельзя. Что-то вы перемудрили с getOrDefault, там всё гораздо проще.
> 3. В getPrice лучше инвертировать условие, а тело else вынести наружу.
> 4. Два `BigDecimal`а для цены в Product многовато. Одного должно хватить (в getPrice-то хватает).

Исправил
